# Generated by Django 5.2.7 on 2026-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppe', '0009_alter_dossierppe_ref_dossier_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file_statut',
            field=models.CharField(choices=[('CAA', 'Contrôle automatique : archivé'), ('CAC', 'Contrôle automatique : en cours'), ('CAE', 'Contrôle automatique : erreurs à corriger'), ('ERR', 'Contrôle automatique : erreur interne'), ('CAV', 'Contrôle automatique : validé'), ('CMS', 'Contrôle manuel : en cours (CMS)'), ('CMC', 'Contrôle manuel : en cours'), ('CME', 'Contrôle manuel : erreurs à corriger'), ('CMV', 'Contrôle manuel : validé'), ('DPV', 'Dossier papier validé')], default='CAC', max_length=3),
        ),
    ]
