# Generated by Django 5.2.7 on 2026-08-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sene_chantiers', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivemeasure',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
        migrations.AlterField(
            model_name='historicalcorrectivemeasure',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
    ]
