# Generated by Django 5.2.7 on 2026-08-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sene_chantiers', '0003_measure_deadline_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chantier',
            options={'ordering': ['-created_at'], 'permissions': [('manage_dossiers', 'Peut utiliser le suivi de chantiers')], 'verbose_name': 'Chantier', 'verbose_name_plural': 'Chantiers'},
        ),
    ]
